
* SlideShow-Simple

** A Implementation of [[https://github.com/apg/slideshow-simple][slideshow-simple]] on Odin!

the objective is to create a slide like structure
that interprete plain .rkt '#lang slideshow/simple'
and that have the habilit to read a custom format,
with the same 'syntax' and semantics, since [[https://github.com/apg/slideshow-simple][SSS]] is so simple (hehe)

the main goal is to be able to generate slides on a simple fashion
without the need to have all the [[https://github.com/racket/racket][Racket]] enviropment on machine
but only a single binary or only [[https://github.com/odin-lang/odin][Odin]] itself!

since with the second goal is been able to generate plain .pdf
and .epub presentations modes, so is not (a pain in the ass)
dificult to generate a .pdf from Slideshow mode of Racket!


** demos


** motivation

have a plain light wight Slide Show Simple Render, on any x86_64 or compatible with Odin programming language, been simple and easy to edit code.

* version of [[https://github.com/odin-lang/odin][Odin]]

dev-2023-06:0c352213
